#!/bin/bash
if [ $# -eq 1 ] ; then
    num=$1
else
    echo "Usage: fibonacci <limit>"
    exit 0
fi
a=1
b=1

for ((i = 0;i < $num; i++))
do
    echo -n "$a "
    n=$(($a + $b))
    a=$b
    b=$n
done
echo ""
